server:
  port: 8080

logging:
  level:
    com.apigoogle: DEBUG

serpapi:
  apikey: 92cb41255f4ea095a973eb0874db3ddae31c6f97ea72730e3717769f2f7a4631

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/serpapi?useSSL=false&serverTimezone=UTC
    username: root
    password: sAurio15!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


